# Generated by Django 4.0.3 on 2022-04-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0002_alter_ratings_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
