# Generated by Django 4.0.3 on 2022-04-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0003_rename_ratings_rating_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
