# Generated by Django 4.0.3 on 2022-04-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0004_alter_rating_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
